warning C4702: unreachable code with try catch blocks.
D:\dev\vcpkg\installed\x64-windows\include\boost\ut.hpp(881) : error C2220: the following warning is treated as an error
D:\dev\vcpkg\installed\x64-windows\include\boost\ut.hpp(881) : warning C4702: unreachable code
D:\dev\vcpkg\installed\x64-windows\include\boost\ut.hpp(881) : warning C4702: unreachable code
https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4702?view=msvc-170
MSVC treats code after return statements as unreachable. By moving the second return inside the try block then there will no longer be two return statements on catch.